name: Test Padel CLI

on:
  workflow_dispatch:

jobs:
  run-padel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build padel-cli
        run: go build -o padel ./cmd/padel

      - name: Run a simple search
        run: ./padel search --location "Dortmund" --json
